---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: travelapp-hpa
  labels:
    app: travelapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: travelapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50