apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: travelapp
spec:
  hosts:
    - travelapp
  http:
  - route:
    - destination:
        host: travelapp
        subset: v1
      weight: 80
    - destination:
        host: travelapp
        subset: v2
      weight: 20
